Lista de producto renderizada.
maurogamboa/js-practice pull request #7
Opened 2022-08-31 13:38 UTC by guillermoecr

2022-08-31 15:02 UTC, maurogamboa commented on src/index.js
> +
eliminar esto
```suggestion
```

2022-08-31 15:02 UTC, maurogamboa commented on index.html
> +					<!--	<div id="listaProductos">
Falta cumplir con este requerimiento del ticket:

> Los productos quemados (hardcoded) en el HTML deberán eliminarse.

2022-08-31 15:02 UTC, maurogamboa commented on index.html
> +    <script src="src/prueba.js"></script>
no es necesario cargar 2 scripts. 
- Mover el codigo de `prueba.js` a `index.js`
- Eliminar `prueba.js`

2022-09-02 20:33 UTC, guillermoecr commented
probando

2022-09-05 15:06 UTC, maurogamboa requested changes

2022-09-05 15:06 UTC, maurogamboa commented on src/index.js
> +function cargarWin() {
que finalidad tiene esta funcion?
`renderizarProductos();` se esta invocando sin argumentos y arroja errores de js ->

![image](https://user-images.githubusercontent.com/52142332/188477643-9f1697f7-739c-4f80-8766-484b79e346ca.png)

2022-09-05 15:06 UTC, maurogamboa commented on src/prueba.js
> +const listaProductos = [
si el archivo `src/prueba.js` no se usa, debería eliminarse

2022-09-05 15:06 UTC, maurogamboa commented on index.html
> +				<br>
por que se agregan estos tags?
```js
				</hr>
				<br>
```

2022-09-06 11:55 UTC, maurogamboa requested changes

2022-09-06 11:55 UTC, maurogamboa commented on src/index.js
> +listaProductos.forEach(renderizarProductos);
esta instruccion deberia moverse adentro de `cargarWin` ->
```js
function cargarWin() {
 listaProductos.forEach(renderizarProductos);
}
```

2022-09-06 11:55 UTC, maurogamboa commented on src/index.js
> +function renderizarProductos(producto) {
Esta funcion deberia estar en singular porque la finalidad  es renderizar un solo producto.
Ademas, deberia moverse a la caperta `src/productos.js`

```suggestion
function renderizarProducto(producto) {
```

2022-09-12 14:29 UTC, maurogamboa approved these changes

2022-09-12 14:29 UTC, merged